# Generated by Django 4.2.8 on 2024-01-29 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "branch",
                    models.CharField(max_length=60, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comprehensive",
            fields=[
                (
                    "roll_no",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("semester", models.IntegerField()),
                ("section", models.CharField(max_length=1)),
                ("cgpa", models.DecimalField(decimal_places=2, max_digits=5)),
                ("total_credits", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                ("is_detained", models.BooleanField(default=False)),
                ("is_gap", models.BooleanField(default=False)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="acad.branch"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "faculty_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("faculty_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Schemes",
            fields=[
                (
                    "scheme",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("st_year", models.IntegerField()),
                ("end_year", models.IntegerField()),
                ("branches", models.ManyToManyField(to="acad.branch")),
            ],
        ),
        migrations.CreateModel(
            name="Subjects",
            fields=[
                (
                    "course_code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("subject", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=6)),
                ("semester", models.IntegerField()),
                ("mode", models.CharField(max_length=10)),
                ("credits", models.DecimalField(decimal_places=2, max_digits=10)),
                ("type", models.CharField(max_length=10)),
                ("end_exam_marks", models.IntegerField()),
                ("cia_marks", models.IntegerField()),
                ("total_marks", models.IntegerField()),
                ("branch", models.ManyToManyField(to="acad.branch")),
                ("scheme", models.ManyToManyField(to="acad.schemes")),
            ],
        ),
        migrations.CreateModel(
            name="Marks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.IntegerField()),
                ("cia_marks", models.IntegerField()),
                ("end_exam_marks", models.IntegerField()),
                ("total_marks", models.IntegerField()),
                ("has_backlog", models.BooleanField(default=True)),
                ("credits", models.DecimalField(decimal_places=1, max_digits=6)),
                (
                    "course_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="acad.subjects"
                    ),
                ),
                (
                    "roll_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="acad.comprehensive",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inactive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inactive_type", models.CharField(max_length=9)),
                ("year", models.IntegerField()),
                ("drop_reason", models.TextField(null=True)),
                ("gap", models.IntegerField(default=0)),
                ("gap_reason", models.TextField(null=True)),
                (
                    "roll_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="acad.comprehensive",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gpa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.IntegerField()),
                ("gpa", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "roll_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="acad.comprehensive",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Faculty_Mapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.IntegerField()),
                ("section", models.CharField(max_length=1)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="acad.branch"
                    ),
                ),
                (
                    "course_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="acad.subjects"
                    ),
                ),
                (
                    "faculty_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="acad.faculty"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Detention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("finished_sem", models.IntegerField()),
                ("dtype", models.CharField(max_length=15)),
                ("dyear", models.IntegerField()),
                (
                    "attendance_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("reason", models.TextField()),
                ("doc_proof", models.FileField(upload_to="documents/")),
                (
                    "last_scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="acad.schemes"
                    ),
                ),
                (
                    "roll_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="acad.comprehensive",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="comprehensive",
            name="current_scheme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="acad.schemes"
            ),
        ),
    ]
