# Generated by Django 4.2.5 on 2024-01-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=60)),
                ('course_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Comprehensive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=60)),
                ('semester', models.IntegerField()),
                ('section', models.CharField(max_length=5)),
                ('scheme', models.CharField(max_length=10)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_credits', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=10)),
                ('finished_sem', models.IntegerField()),
                ('last_scheme', models.CharField(max_length=10)),
                ('reason', models.TextField()),
                ('doc_proof', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Electives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=10)),
                ('semester', models.IntegerField()),
                ('category', models.CharField(max_length=6)),
                ('chosen_subject', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inactive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=10)),
                ('inactive_type', models.CharField(max_length=9)),
                ('year', models.IntegerField()),
                ('drop_reason', models.TextField(null=True)),
                ('gap_reason', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=10)),
                ('semester', models.IntegerField()),
                ('subject', models.CharField(max_length=50)),
                ('internal_marks', models.IntegerField()),
                ('external_marks', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('has_backlog', models.BooleanField(default=True)),
                ('credits', models.DecimalField(decimal_places=1, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Subject_Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=10)),
                ('course_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=6)),
                ('scheme', models.IntegerField()),
                ('semester', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('credits', models.DecimalField(decimal_places=2, max_digits=10)),
                ('end_exam_marks', models.IntegerField()),
                ('cia_marks', models.IntegerField()),
                ('total_marks', models.IntegerField()),
            ],
        ),
    ]
