# Generated by Django 4.2.8 on 2024-01-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acad", "0002_faculty_mapping_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="YourModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
    ]
