# Generated by Django 4.2.8 on 2024-01-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acad", "0003_yourmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gpa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll_no", models.CharField(max_length=10)),
                ("semester", models.IntegerField()),
                ("gpa", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RemoveField(model_name="comprehensive", name="gpa",),
    ]
