# Generated by Django 4.2.5 on 2024-01-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0004_gpa_remove_comprehensive_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='detention',
            name='dyear',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inactive',
            name='is_gap',
            field=models.BooleanField(default=False),
        ),
    ]
