# Generated by Django 4.2.8 on 2024-01-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acad", "0004_gpa_remove_comprehensive_gpa"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schemes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheme", models.CharField(max_length=10)),
                ("st_year", models.IntegerField()),
                ("end_year", models.IntegerField()),
                ("branches", models.JSONField()),
            ],
        ),
        migrations.DeleteModel(name="YourModel",),
        migrations.AddField(
            model_name="comprehensive",
            name="is_detained",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="inactive", name="gap", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="comprehensive",
            name="section",
            field=models.CharField(max_length=1),
        ),
    ]
