# Generated by Django 4.2.8 on 2024-01-10 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("acad", "0005_detention_dyear_inactive_is_gap"),
        ("acad", "0005_schemes_delete_yourmodel_comprehensive_is_detained_and_more"),
    ]

    operations = []
