# Generated by Django 4.2.5 on 2024-01-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0006_merge_20240110_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inactive',
            name='is_gap',
        ),
        migrations.AlterField(
            model_name='comprehensive',
            name='is_detained',
            field=models.BooleanField(default=False),
        ),
    ]
