# Generated by Django 4.2.5 on 2024-01-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0007_remove_inactive_is_gap_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='type',
            new_name='mode',
        ),
        migrations.AddField(
            model_name='comprehensive',
            name='is_gap',
            field=models.BooleanField(default=False),
        ),
    ]
