# Generated by Django 4.2.5 on 2024-01-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0008_rename_type_subjects_mode_comprehensive_is_gap'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='type',
            field=models.CharField(default='General', max_length=10),
            preserve_default=False,
        ),
    ]
