# Generated by Django 4.2.8 on 2024-01-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acad", "0009_subjects_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="detention",
            name="dtype",
            field=models.CharField(default="Condonation", max_length=15),
            preserve_default=False,
        ),
    ]
