# Generated by Django 4.2.8 on 2024-01-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acad", "0010_detention_dtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="detention",
            name="attendance_percentage",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
    ]
