# Generated by Django 4.2.8 on 2024-01-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acad", "0011_detention_attendance_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjects", name="semester", field=models.IntegerField(),
        ),
    ]
