# Generated by Django 4.2.5 on 2024-01-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0012_alter_subjects_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemes',
            name='branches',
            field=models.TextField(),
        ),
    ]
