# Generated by Django 4.2.5 on 2024-01-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0013_alter_schemes_branches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='scheme',
            field=models.CharField(max_length=10),
        ),
    ]
